box::use(
  sf,
  tidyr[separate],
)

#' Convert api location strings into a latitude and longitude column.
#'
#' api /plots returns plot locations in a single string: "POINT(-7638030.938909297 5597680.762257315)"
#' This function extracts the X and Y location information from the string and stores it as two columns in a
#' data.table.
#'
#' @param plot_dt - a data.table response from app/logic/load_data_api$get_all_plot_loc
#' @param location_col - string of column name containing location string
#' @param output_col - list of 2 column names populated with X and Y coordinates in the return data.table.
#' @return a data.table containing output_col with X and Y coordinates
#' @export
extract_lat_long_from_api <- function(plot_dt,
                                      location_col = "location",
                                      output_col = c("Longitude", "Latitude")) {
  plot_dt[, (location_col) := gsub("[POINT()]", "", get(location_col))]
  plot_dt <- separate(plot_dt, col = location_col, into = output_col, sep = " ")
  plot_dt
}

#' Define the coordinate system for X and Y coordinates
#'
#' @param plot_dt - a data.table containing plot locations.
#' @param coord_col - a list containing the column names for the X and Y locations in plot_dt.
#' @param imon_crs - int defining EPSG number of the coordinate reference system to be assigned.
#' @return a data.table with a defined CRS in a geometry column
#' @export
set_crs <- function(plot_dt,
                    coord_col = c("Longitude", "Latitude"),
                    imon_crs = 3857) {
  sf$st_as_sf(plot_dt,
    coords = coord_col,
    crs = imon_crs
  )
}

#' Convert one Coordinate Reference System (CRS) to another.
#'
#' Takes a data.table with column 'geometry' of a known CRS and converts it to a new CRS. If CRS is not
#' defined for a data.table, first apply `set_crs()` before applying this function.
#'
#' @param pts - a data.table containing a geometry column with a defined CRS.
#' @params target_crs - int defining EPSG number for desired CRS
#' @export
convert_crs <- function(pts,
                        target_crs = 4326) {
  # Transform to WGS84 (EPSG:4326)
  sf$st_transform(pts, target_crs)
}

#' Extract locatino information from api return and convert into leaflet mappable points.
#'
#' Import a data.table from the api, extract location information, and convert it into the Coordinate
#' Reference System (CRS) used by leaflet.
#'
#' @param plot_dt -  data.table containing X and Y coordinates as a string in the format
#'        "POINT(-7638030.938909297 5597680.762257315)"
#' @param location_col - string defining the column that contains the location string in plot_dt.
#' @param api_crs - int defning the EPSG number of the CRS of coordinates from the api
#' @param leaflet_crs - in defining the EPSG number of the CRS needed for mapping in the leaflet package.
#' @return a data.table with Latitude and Longitude columns in leaflet CRS
#' @export
convert_api_loc2leaflet <- function(plot_dt,
                                    location_col = "location",
                                    api_crs = 3857,
                                    leaflet_crs = 4326) {
  # convert POINT(-9078227.3364 3934562.5600000024) into lat long
  plot_dt <- extract_lat_long_from_api(plot_dt, location_col, output_col = c("Longitude", "Latitude"))

  plots_crs_api <- set_crs(plot_dt, imon_crs = api_crs, coord_col = c("Longitude", "Latitude"))

  plots_crs_leaflet <- convert_crs(plots_crs_api, leaflet_crs)

  # Extract coordinates back into data table
  coords_dt <- sf$st_coordinates(plots_crs_leaflet)

  # assign coordinates to data table
  plot_dt$Longitude <- coords_dt[, 1]
  plot_dt$Latitude <- coords_dt[, 2]

  plot_dt
}

#' Get a data.table of plots in the current view extent.
#'
#' Assumes an input data.table of scans formated by app/logic/manage_data$build_scan_loc_dt. The input scans
#' must have the following column names: c(Lattitude, Longitude, site, plot). Scans will be filtered to a
#' single row per plot within the map extent.
#'
#' @param scans - a data.table generated by app/logic/manage_data$build_scan_loc_dt
#' @param bounds - a shiny server input from a leaflet map.
#' @return a data.table of plots filtered
#' @export
get_plots_in_view <- function(scans, bounds) {
  in_view <- scans[
    Latitude >= bounds$south & Latitude <= bounds$north &
      Longitude >= bounds$west & Longitude <= bounds$east
  ]
  # remove re-scans
  unique(in_view, by = c("site", "plot"))
}

#' Parse the clickID. When a marker is clicked on, parse it's id.
#'
#' Assumes a maximum of 2 parts to parse in ID.
#'
#' @param click - a click object from
#' @export
parse_click_id <- function(click, sep = "-", labels = c("site", "plot")) {
  # extract site and plot from the click id
  parts <- strsplit(click$id, sep)[[1]]
  if (length(parts) != 2) {
    return(NULL)
  } else {
    part_list <- as.list(parts)
    names(part_list) <- labels
    part_list
  }
}

#' Return  location information for scans in the metrics data.table
#'
#' Location information is only stored in session$userData$scan_selection. This function takes a data.table
#' with output data, such as metrics, and returns the corresponding locatoin information based on site,
#' plot, date, and scanner_id.
#'
#' @param metric_dt - a data.table with measurement data and columns with unique site, plot, date,
#'        scanner_id's
#' @param scan_dt - a data.table from sessoin$userData$scan_selection
#' @return a data.table from sessoin$userData$scan_selection including lattitude and longitude columns in
#'         leaflet CRS.
#' @export
get_metric_loc <- function(metric_dt, scan_dt) {
  scan_dt[metric_dt, on = .(site, plot, date, scanner_id), nomatch = 0, .SD]
}
