name: Tests and lintr
on:
  # Run on pushes to 'main' branch
  push:
    branches:
      - main
      - development
  # Run on any opened pull request
  pull_request:
  # Run manually via GitHub Actions website
  workflow_dispatch:
permissions:
  contents: read
jobs:
  tests:
    name: Tests and lintr
    runs-on: ubuntu-22.04
    # clearly identify the paths that all steps need to use, as well as security tokens
    env:
      R_LIBS_USER: /home/runner/work/_temp/Library
      RENV_PATHS_ROOT: /home/runner/work/_temp/renv
      CRAN_MIRROR: https://packagemanager.posit.co/cran/2025-07-01
      # lock it all to a url date with no binaries
      RENV_CONFIG_REPOS_OVERRIDE: ${{ env.CRAN_MIRROR }}
      # force it to bypass azure.archive.unbuntu.com or packages.microsoft.com which usually fail
      RSPM: ${{ env.CRAN_MIRROR }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # load OS (unbuntu) from cache
      - name: Restore apt cache
        id: cache-apt-restore
        uses: actions/cache/restore@v5
        with:
          path: /var/cache/apt/archives
          # current configuration will create a new cache every time test.yml changes.
          key: apt-${{ runner.os }}-${{ hashFiles('.github/workflows/test.yml') }}

      - name: Setup system dependencies
        if: steps.cache-apt-restore.outputs.cache-hit != 'true'
        # terra requires gdal and sql libraries
        run: |
          # 1. Force the runner to bypass the broken Azure mirror
          sudo sed -i 's|deb http://azure.archive.ubuntu.com/ubuntu|deb https://archive.ubuntu.com/ubuntu|g' /etc/apt/sources.list
          sudo sed -i 's|deb-src http://azure.archive.ubuntu.com/ubuntu|deb-src http://archive.ubuntu.com/ubuntu|g' /etc/apt/sources.list
          
          # 2. Add aggressive timeout limits so it never hangs for an hour again (and avoids Microsoft's ipv6 errors)
          sudo apt-get \
            -o Acquire::ForceIPv4=true \
            -o Acquire::http::Timeout="10" \
            -o Acquire::ftp::Timeout="10" \
            update
    
          packages=(
            libgdal-dev
            libgeos-dev
            libproj-dev
            libsqlite3-dev
          )
          sudo apt-get install --yes --no-install-recommends "${packages[@]}"

      # ----R installation environment----------------------------------------------
      - name: Restore R cache
        id: cache-r-restore
        uses: actions/cache/restore@v5
        with:
          path: /opt/R
          key: R-${{ runner.os }}-${{ hashFiles('renv.lock') }}

      - name: Setup R
        if: steps.cache-r-restore.outputs.cache-hit != 'true'
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: renv

      # always save if the cache is new (not reloaded)
      - name: Save R cache
        id: cache-r-save
        if: always() && steps.cache-r-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          path: /opt/R
          key: R-${{ runner.os }}-${{ hashFiles('renv.lock') }}

      - name: Restore renv cache
        id: cache-renv-restore
        uses: actions/cache/restore@v5
        with:
          path: ${{ env.RENV_PATHS_ROOT}}
          # any change to renv.lock will replace the cache
          key: renv-${{ runner.os }}-${{ hashFiles('renv.lock') }}
          restore-keys: renv-${{ runner.os }}-

      - name: Install renv and dependencies
        if: steps.cache-renv-restore.outputs.cache-hit != 'true'
        shell: Rscript {0}
        env:
          # Require the runner to pull down source code and compile
          RENV_CONFIG_REPOS_TYPE: "source"
        run: |
          # 1. Define the specific target Linux mirror for the GitHub Runner execution env
          linux_mirror <- c(CRAN = Sys.getenv("CRAN_MIRROR"))
          options(repos = linux_mirror)
          options(renv.config.install.staged = FALSE)
          options(pkgType = "source")
          
          # Ensure the directory explicitly exists in the runner workspace and is first in the path
          user_lib <- Sys.getenv("R_LIBS_USER")
          if (!dir.exists(user_lib)) {
            dir.create(user_lib, recursive = TRUE)
          }
          .libPaths(c(user_lib, .libPaths()))
          
          # install renv
          install.packages(
            "renv",
            lib = user_lib,
            repos = linux_mirror
          )
          
          # manually setup all R dependencies from renv.lock
          library(renv, lib.loc = user_lib)
          renv::restore(prompt = FALSE, repos= linux_mirror)

      - name: Save renv cache
        id: cache-renv-save
        if: always() && steps.cache-renv-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          path: ${{ env.RENV_PATHS_ROOT}}
          # any change to renv.lock will replace the cache
          key: renv-${{ runner.os }}-${{ hashFiles('renv.lock') }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 24

      # save entire OS env, including any installations made by R (like gdal)
      # remove files that require sudo for access before caching
      - name: Prepare apt cache for saving
        if: always() && steps.cache-apt-restore.outputs.cache-hit != 'true'
        run: |
          sudo chmod -R a+r /var/cache/apt/archives
          sudo rm -f /var/cache/apt/archives/lock
          sudo rm -rf /var/cache/apt/archives/partial

      - name: Save apt cache
        id: cache-apt-save
        if: always() && steps.cache-apt-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          path: /var/cache/apt/archives
          # current configuration will create a new cache every time test.yml changes.
          key: apt-${{ runner.os }}-${{ hashFiles('.github/workflows/test.yml') }}

      #-----Tests and linting----------------------------------------------------------
      - name: Lint R
        if: always()
        shell: Rscript {0}
        run: rhino::lint_r()

      - name: Lint JavaScript
        if: always()
        shell: Rscript {0}
        run: rhino::lint_js()

      - name: Lint Sass
        if: always()
        shell: Rscript {0}
        run: rhino::lint_sass()

      - name: Build JavaScript
        if: always()
        shell: Rscript {0}
        run: rhino::build_js()

      - name: Build Sass
        if: always()
        shell: Rscript {0}
        run: rhino::build_sass()

      - name: Run R unit tests
        if: always()
        shell: Rscript {0}
        run: rhino::test_r()

      - name: Run Cypress end-to-end tests
        if: github.ref_name == 'main'
        uses: cypress-io/github-action@v6
        with:
          working-directory: .rhino # Created by earlier commands which use Node.js
          start: npm run run-app
          project: ../tests
          wait-on: 'http://localhost:3333/'
          wait-on-timeout: 60
