name: Tests and lintr
on:
  # Run on pushes to 'main' branch
  push:
    branches:
      - main
      - development
  # Run on any opened pull request
  pull_request:
  # Run manually via GitHub Actions website
  workflow_dispatch:
permissions:
  contents: read
jobs:
  tests:
    name: Tests and lintr
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # load OS (unbuntu) from cache
      - name: Restore apt cache
        id: cache-apt-restore
        uses: actions/cache/restore@v5
        with:
          path: /var/cache/apt/archives
          # current configuration will create a new cache every time test.yml changes.
          key: apt-${{ runner.os }}-${{ hashFiles('.github/workflows/test.yml') }}

      - name: Setup system dependencies
        if: steps.cache-apt-restore.outputs.cache-hit != 'true'
        # terra requires gdal and sql libraries
        run: |
          # 1. Force the runner to bypass the broken Azure mirror
          sudo sed -i 's| http://azure.archive.ubuntu.com/ubuntu |http://ubuntu.com|g' /etc/apt/sources.list
          
          # 2. Add aggressive timeout limits so it never hangs for an hour again (and avoids Microsoft's ipv6 errors)
          sudo apt-get \
            -o Acquire::ForceIPv4=true \
            -o Acquire::http::Timeout="10" \
            -o Acquire::ftp::Timeout="10" \
            update
    
          packages=(
            libgdal-dev
            libgeos-dev
            libproj-dev
            libsqlite3-dev
          )
          sudo apt-get install --yes --no-install-recommends "${packages[@]}"

      # ----R installation environment----------------------------------------------
      - name: Restore R cache
        id: cache-r-restore
        uses: actions/cache/restore@v5
        with:
          path: /opt/R
          key: R-${{ runner.os }}-${{ hashFiles('renv.lock') }}

      - name: Setup R
        if: steps.cache-r-restore.outputs.cache-hit != 'true'
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: renv
        env:
          # force it to bypass azure.archive.unbuntu.com or packages.microsoft.com which usually fail
          RSPM: "https://packagemanager.posit.co/cran/__linux__/jammy/latest"

      # always save if the cache is new (not reloaded)
      - name: Save R cache
        id: cache-r-save
        if: always() && steps.cache-r-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          path: /opt/R
          key: R-${{ runner.os }}-${{ hashFiles('renv.lock') }}

      - name: Restore renv cache
        id: cache-renv-restore
        uses: actions/cache/restore@v5
        with:
          path: /home/runner/work/_temp/renv
          # any change to renv.lock will replace the cache
          key: renv-${{ runner.os }}-${{ hashFiles('renv.lock') }}
          restore-keys: renv-${{ runner.os }}-

      - name: Install renv
        if: steps.cache-renv-restore.outputs.cache-hit != 'true'
        shell: Rscript {0}
        env:
          R_LIBS_USER: /home/runner/work/_temp/Library
        run: |
          # Ensure the directory explicitly exists in the runner workspace
          if (!dir.exists(Sys.getenv("R_LIBS_USER"))) {
            dir.create(Sys.getenv("R_LIBS_USER"), recursive = TRUE)
          }
          install.packages(
            "renv",
            lib = Sys.getenv("R_LIBS_USER"),
            repos = "https://packagemanager.posit.co/cran/2025-07-01"
          )

      - name: Setup R dependencies
        if: steps.cache-renv-restore.outputs.cache-hit != 'true'
        uses: r-lib/actions/setup-renv@v2
        # make sure it doesn't try to create its own cache
        with:
          bypass-cache: true
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
          R_LIBS_USER: /home/runner/work/_temp/Library
          # force it to skip the azure/microsoft downloads, which are unreliable.
          RENV_CONFIG_REPOS_OVERRIDE: "https://packagemanager.posit.co/cran/__linux__/jammy/2025-07-01"

      - name: Save renv cache
        id: cache-renv-save
        if: always() && steps.cache-renv-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          path: /home/runner/work/_temp/renv
          # any change to renv.lock will replace the cache
          key: renv-${{ runner.os }}-${{ hashFiles('renv.lock') }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 24

      # save entire OS env, including any installations made by R (like gdal)
      # remove files that require sudo for access before caching
      - name: Prepare apt cache for saving
        if: always() && steps.cache-apt-restore.outputs.cache-hit != 'true'
        run: |
          sudo chmod -R a+r /var/cache/apt/archives
          sudo rm -f /var/cache/apt/archives/lock
          sudo rm -rf /var/cache/apt/archives/partial

      - name: Save apt cache
        id: cache-apt-save
        if: always() && steps.cache-apt-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          path: /var/cache/apt/archives
          # current configuration will create a new cache every time test.yml changes.
          key: apt-${{ runner.os }}-${{ hashFiles('.github/workflows/test.yml') }}

      #-----Tests and linting----------------------------------------------------------
      - name: Lint R
        if: always()
        shell: Rscript {0}
        run: rhino::lint_r()

      - name: Lint JavaScript
        if: always()
        shell: Rscript {0}
        run: rhino::lint_js()

      - name: Lint Sass
        if: always()
        shell: Rscript {0}
        run: rhino::lint_sass()

      - name: Build JavaScript
        if: always()
        shell: Rscript {0}
        run: rhino::build_js()

      - name: Build Sass
        if: always()
        shell: Rscript {0}
        run: rhino::build_sass()

      - name: Run R unit tests
        if: always()
        shell: Rscript {0}
        run: rhino::test_r()

      - name: Run Cypress end-to-end tests
        if: github.ref_name == 'main'
        uses: cypress-io/github-action@v6
        with:
          working-directory: .rhino # Created by earlier commands which use Node.js
          start: npm run run-app
          project: ../tests
          wait-on: 'http://localhost:3333/'
          wait-on-timeout: 60
